### ISSUE TITLE
Library is breaking tests: can't find module 'uuid/v1' in sequelize utilities

### ISSUE THREAD

**Issue by dansundy** [ysocorp/koa2-ratelimit#29]
I'd love to use this library but it is breaking my tests with the following error:

```
Cannot find module 'uuid/v1' from 'node_modules/sequelize/lib/utils.js'

Require stack:
      node_modules/sequelize/lib/utils.js
      node_modules/sequelize/lib/sequelize.js
      node_modules/sequelize/index.js
      node_modules/koa2-ratelimit/src/SequelizeStore.js
      node_modules/koa2-ratelimit/src/index.js
      server/server.js
      server/heartbeat/__tests__/heartbeat-requests.test.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (node_modules/sequelize/lib/utils.js:6:16)
```

This happens as soon as I require the module in my app:

```
const rateLimit = require('koa2-ratelimit').RateLimit
```

This is how I'm using it in my `server.js` file:

```
app.use(
  rateLimit.middleware({
    interval: { min: 15 }, // 15 minutes = 15*60*1000
    max: 100, // limit each IP to 100 requests per interval
  })
)
```

I am not using a store. For now I am conditionally adding the block for production but I'm wondering why sequelize is being added at all if I'm not using it.

Thanks for your time!

**Comment by julienwilmet** [comment]
Is this still relevant?
